<?php
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
$array = ["Kopparberg Strawberry & Lime",
"Kopparberg Mixed Fruit",
"Kopparberg Pear",
"Bulmers No17",
"WKD",
"Smirnoff Ice",
"Corona",
"Budweiser",
"Peroni",
"Desperados",
"Desperados Red",
"Sol",
"Beck’s",
"Antica Sambuca",
"J2O",
"Pepsi Max",
"Diet Pepsi",
"Pepsi",
"R White’s Lemonade",
"old jamaica ginger beer",
"moster ultra",
"monster ripper",
"Sanpellegrino",
"Innocent™ Super Smoothie Energise",
"Strathmore Spring Water",
"Fruit juice",
"Freshly brewed filter coffee",
"Cappuccino",
"Latte",
"Americano",
"Mocha",
"Espresso",
"Tea",
"Hot Chocolate",
"Iced frappe",
"Uprising Treason West Coast IPA",
"Craft y Dan 13 Guns American IPA",
"Flying Dog Snake Dog IPA",
"Sixpoint Resin Double IPA",
"Sixpoint Bengali IPA",
"Bud Light",
"Carlsbergs",
"Fosters",
"Carling",
"Coors light",
"tuborg",
"stella artois",
"san miguel",
"kronenbourg 1664",
"heineken",
"Magners",
"Strongbow",
"Thatchers Gold",
"Strongbow Dark Fruit",
"Guest ciders",
"Birra Moretti",
"Tsingtao",
"Erdinger",
"Tyskie Gronie",
"Krombacher Pils",
"Tucher Helles Hefe Weizen",
"Newcastle Brown Ale",
"Efes",
"Baltika 7",
"Estrella Galicia",
"Oakham Ales Green Devil IPA",
"Shipyard Rye Pale Ale",
"Devils Backbone – American IPA",
"Blue Moon Belgian White",
"BrewDog Punk IPA",
"Lagunitas IPA",
"Brooklyn Lager",
"shipyard",
"sharps doom bar",
"guest ales",
"ruddles",
"abbot ale",
"jhon smith",
"guinness",
"hazy hog cloudy english cider",
"angry orchard",
"aspall suffolk cyder",
"Magners Original",
"Hooch",
"Beck’s Blue",
"Erdinger Alkoholfrei",
"Captain Morgan Original Spiced Gold",
"Captain Morgan White",
"Red Leg Spiced",
"Bacardi Carta Blanca",
"Appleton Estate",
"Kraken Black Spiced",
"Havana Club 7-year-old",
"Ron Zacapa 23-year-old",
"Rum Storm",
"Stolichnaya",
"Skyy",
"Absolut",
"Absolut Vanilia",
"Smirnoff Red",
"Vodka, Lime and Soda",
"Bell’s",
"Haig Club Clubman",
"Jameson Irish Whiskey",
"Southern Comfort",
"Jim Beam Bourbon Whiskey",
"Buffalo Trace Bourbon",
"Jack Daniel’s",
"Jura Origin 10-year-old",
"Glenfiddich",
"Glenmorangie",
"Gordon’s",
"Portobello Road",
"Bombay Sapphire",
"Tanqueray",
"Martin Miller’s",
"Sipsmith",
"Tanqueray No. Ten",
"Gin Fizz",
"Chase",
"Belvedere",
"Courvoisier VS",
"Hennessy Fine de Cognac",
"Chambord Black Raspberry Liqueur",
"Disaronno Amaretto",
"Fireball Cinnamon Whisky Liqueur",
"SOURZ",
"Sauvignon Blanc",
"Chardonnay",
"Pinot Grigio",
"Cabernet Sauvignon",
"Merlot",
"White Zinfandel Rosé",
"Hardys Chardonnay",
"Hardys Pinot Grigio",
"Bolla Pinot Grigio",
"Villa Maria Sauvignon Blanc",
"Hardys Shiraz",
"Casillero del Diablo Cabernet Sauvignon",
"Trivento Malbec",
"Grant Burge Shiraz Benchmark",
"Hardys Rosé",
"Blossom Hill White Zinfandel Rosé",
"Chambord Royal",
"Mojito",
"long island iced tea",
"rum punch",
"very cherry",
"sex on the beach",
"porn star martini",
"purple rain",
"woo woo",
"blue lagoon",
"the godfather",
"classic pimms",
"Teresa Rizzi",
"Prosecco",
"Teresa Rizzi Sparkling Rosé",
"Buck’s Fizz",
"Moët & Chandon Brut Imperial",
"Jägerbomb",
"Fireballbomb",
"Jose Cuervo Especial Tequila",
"Smirnoff vodka and Monster"];
echo $array[array_rand($array)];